/**
 * Convert/translate Youtube´s list of video meta data to intended format.
 * TODO: this should be in another place OR be generated by schema
 * @param {*} sourceItems 
 */
function _getItemsMeta(sourceItems) {
    var metaItems = []
    sourceItems.map(function (item) {
        //First tag shall always be the title of the channel
            var tags = item.systematikpfad || [];
            tags.unshift("LEIFIphysik");
        metaItems.push({
            originId: item.id,
            providerName: item.einsteller,
            url: item.url_datensatz,
            title: item.title,
            description: item.beschreibung || "No Description",
            thumbnail: item.quelle_logo_url,
            contentCategory: 'atomic',
            subject: "Physik",
            tags: tags,
            mimeType: 'text/html',
            licenses: [item.rechte]
        })
    })
    return metaItems;
}


module.exports = {
    crawl: function (config, fetcher, fetchCallback) {
        _config = config;
        fetcher.fetch({
            xml_url: _config.xml_url
        }, function (sourceItems) {
            fetchCallback(_getItemsMeta(sourceItems));
        })

    },
    configSpec : {
        xml_url: {
            env: "XML_URL",
            type: "string",
            default: "XML_URL as string"
        }
    }
}
